"""create summaries table

Revision ID: e87bc02e79d8
Revises: faaa132fa80e
Create Date: 2026-09-02 11:19:48.304977

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e87bc02e79d8'
down_revision: str | Sequence[str] | None = 'faaa132fa80e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash', 'model_name', 'prompt_version', name='uq_summaries_article_and_config')
    )
    op.create_index('ix_summaries_url_hash', 'summaries', ['url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_summaries_url_hash', table_name='summaries')
    op.drop_table('summaries')
    # ### end Alembic commands ###
